//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factuur
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactuurDB : DbContext
    {
        public FactuurDB()
            : base("name=FactuurDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<debiteuren> debiteuren { get; set; }
        public virtual DbSet<facturen> facturen { get; set; }
        public virtual DbSet<factuur_items> factuur_items { get; set; }
        public virtual DbSet<producten> producten { get; set; }
    }
}
