//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factuur
{
    using System;
    using System.Collections.Generic;
    
    public partial class factuur_items
    {
        public int ID { get; set; }
        public int FactuurID { get; set; }
        public int ProductID { get; set; }
        public int Aantal { get; set; }
    
        public virtual facturen facturen { get; set; }
        public virtual producten producten { get; set; }
    }
}
