//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factuur
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturen()
        {
            this.factuur_items = new HashSet<factuur_items>();
        }
    
        public int Factuurnummer { get; set; }
        public System.DateTime Factuurdatum { get; set; }
        public Nullable<decimal> Totaalbedrag { get; set; }
        public int Debiteur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factuur_items> factuur_items { get; set; }
        public virtual debiteuren debiteuren { get; set; }
    }
}
